GameHistory Project/videogame_keys/marketplace/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('listing/<int:listing_id>/', views.listing_detail, name='listing_detail'),
    path('create_listing/', views.create_listing, name='create_listing'),
    path('listing/<int:listing_id>/', views.listing_detail, name='listing_detail'),
    path('listing/<int:listing_id>/add_review/', views.add_review, name='add_review'),
    path('delete_listing/<int:listing_id>/', views.delete_listing, name='delete_listing'),
    path('buy_listing/<int:listing_id>/', views.buy_listing, name='buy_listing'),
    path('add_quantity/<int:listing_id>/', views.add_quantity, name='add_quantity'),
    path('registration/signup/', views.signup, name='signup'),
    path('create/', views.create_listing, name='create_listing'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'), 
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path('profile/', views.user_profile, name='user_profile'),
    path("user_purchases/", views.user_purchases, name="user_purchases"),
    path('search/', views.search_listings, name='search_listings'),
    path('listing/<int:listing_id>/offer/', views.create_offer, name='create_offer'),
    path('manage_offers/', views.manage_offers, name='manage_offers'),
    path('offer/<int:offer_id>/<str:response>/', views.respond_to_offer, name='respond_to_offer'),
    path('listing/<int:listing_id>/modify', views.edit_listing, name='edit_listing'),
]

GameHistory Project/videogame_keys/videogame_keys/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('marketplace.urls')),
    path('registration/', include('django.contrib.auth.urls')),  # Assicurati che questa riga sia presente
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),  # Sovrascrivi il logout
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
]

GameHistory Project/videogame_keys/marketplace/models.py
# Create your models here.
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
import uuid


class Game(models.Model):
    title = models.CharField(max_length=100)
    release_date = models.DateField()
    genre = models.CharField(max_length=50)
    category = models.CharField(max_length=50)
    platform = models.CharField(max_length=50)
    description = models.TextField()

    def __str__(self):
        return self.title

# classe che rappresenta il fulcro del programma, perchè di creare degli annunci
class Listing(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)  # Foreign Key sullo user
    game = models.ForeignKey(Game, on_delete=models.CASCADE)  # Foreign Key sul gioco collegato
    price = models.DecimalField(max_digits=10, decimal_places=2) # campo del prezzo
    quantity = models.PositiveIntegerField(default=1)  # campo della quantità disponibile dell'annuncio
    created_at = models.DateTimeField(auto_now_add=True)  # campo che riguarda la data di pubblicazione)
    is_available = models.BooleanField(default=True)  # campo che riguarda la disponibilità per la visione sulla home principale

    def save(self, *args, **kwargs):  # salvataggio sul dataset
        self.is_available = self.quantity > 0
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.game.title} - {self.price} €"
    
# classe che permette di comprare i diversi annunci presenti sul sito
class Purchase(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE) # Foreign Key sullo user
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE)  #  Foreign Key sull'annuncio
    purchase_date = models.DateTimeField(auto_now_add=True) # campo della data
    key = models.CharField(max_length=19, null=True, blank=True)  # campo della chiave
    is_a_offer = models.BooleanField(default=False)
    
    def save(self, *args, **kwargs):  # salva sul dataset
        if not self.key:
            # Generate game key if not already set
            self.key = self.generate_game_key()
        super().save(*args, **kwargs)

    def generate_game_key(self): # generatore per la chiave fittizia
        return '-'.join([str(uuid.uuid4().hex)[:4].upper() for _ in range(4)])  # def per la generazione casuale di una chiave in formato XXXX-XXXX-XXXX

    def __str__(self): 
        return f"Acquisto di {self.listing.game.title} da {self.user.username} nel giorno {self.purchase_date}"

# classe che permette di commentare i diversi annunci presenti sul sito
class Comment(models.Model):
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Commento di {self.user.username} sul gioco/annuncio: {self.listing.game.title}"
    
# Classe che permette la di recensire i diversi annunci presenti sul sito
class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reviews_given')
    seller = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reviews_received')
    rating = models.IntegerField()
    comment = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Recensione di {self.user.username} per {self.seller.username} di {self.rating} stelle"

# Classe che permette di effettuare un'offerta ad un'annuncio
class Offer(models.Model):
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name='offers')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    offer_price = models.DecimalField(max_digits=10, decimal_places=2)
    accepted = models.BooleanField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Offerta: {self.offer_price} €, da {self.user.username} per il gioco/annuncio: {self.listing.game.title}"
        
    def save(self, *args, **kwargs):
        self.clean()
        super().save(*args, **kwargs)

GameHistory Project/videogame_keys/marketplace/forms.py
# marketplace/forms.py
from django import forms
from .models import Game, Listing, Comment, Review, Offer


class ListingForm(forms.ModelForm):
    class Meta:
        model = Listing
        fields = ['price', 'quantity']

class GameForm(forms.ModelForm):
    class Meta:
        model = Game
        fields = ['title', 'release_date', 'genre', 'category', 'platform', 'description']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['rating', 'comment']

class SearchForm(forms.Form):
    query = forms.CharField(label='Search', max_length=255)

class OfferForm(forms.ModelForm):
    class Meta:
        model = Offer
        fields = ['offer_price']

    def __init__(self, *args, **kwargs):
        self.listing = kwargs.pop('listing')
        super(OfferForm, self).__init__(*args, **kwargs)

GameHistory Project/videogame_keys/marketplace/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import *
from django.db.models import Q
from .forms import ListingForm, GameForm, CommentForm, ReviewForm, SearchForm, OfferForm
from django.contrib.auth.models import AnonymousUser  # Importa l'AnonymousUser
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.views.decorators.http import require_POST


def home(request):
    listings = Listing.objects.filter(is_available=True)  # Filtra solo gli annunci disponibili
    context = {
        'listings': listings,
    }

    return render(request, 'marketplace/home.html', context)

@login_required
def edit_listing(request, listing_id):
    listing = get_object_or_404(Listing, pk=listing_id)
    game = listing.game

    if request.user != listing.user:
        messages.error(request, "Non è il tuo annuncio!")
        return redirect('home')

    if request.method == 'POST':
        listing_form = ListingForm(request.POST, request.FILES, instance=listing)
        game_form = GameForm(request.POST, request.FILES, instance=game)

        if listing_form.is_valid() and game_form.is_valid():
            game_instance = game_form.save()
            listing_instance = listing_form.save(commit=False)
            listing_instance.game = game_instance
            listing_instance.user = request.user

            if listing_instance.price > 0:
                listing_instance.save()
                messages.success(request, "Annuncio modificato con successo!")
                return redirect('listing_detail', listing_id=listing.id)
            else:
                messages.error(request, "Non è possibile avere un prezzo negativo!")
    
    else:
        listing_form = ListingForm(instance=listing)
        game_form = GameForm(instance=game)

    return render(request, 'marketplace/edit_listing.html', {
        'listing' : listing,
        'listing_form': listing_form,
        'game_form': game_form,
    })


@login_required
def add_review(request, listing_id):
    listing = get_object_or_404(Listing, pk=listing_id)
    seller = listing.user
    # Controlla se l'utente sta cercando di recensire se stesso
    if request.user == seller:
        messages.error(request, "Non puoi fare una recensione a te stesso.")
        return redirect('listing_detail', listing_id=listing.id)


    existing_review = Review.objects.filter(user_id=request.user.id, seller_id=seller.id).first()
    if existing_review:
        messages.success(request, "Hai già recensito il venditore")
        return redirect('listing_detail', listing_id=listing.id)
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.user = request.user
            review.seller = seller
            review.save()
            messages.success(request, f"Recensione inviata con successo!")
            return redirect('listing_detail', listing_id=listing.id)
    else:
        form = ReviewForm()

    return render(request, 'marketplace/add_review.html', {
        'listing': listing,
        'form': form,
    })


def listing_detail(request, listing_id):
    listing = get_object_or_404(Listing, pk=listing_id)
    comments = listing.comments.all()
    reviews = Review.objects.filter(seller=listing.user)
    average_rating = reviews.aggregate(models.Avg('rating'))['rating__avg']

    if request.user == listing.user:
        is_owner = True
    else:
        is_owner = False

    if request.method == 'POST':
        if request.user.is_authenticated:
            form = CommentForm(request.POST)
            if form.is_valid():
                comment = form.save(commit=False)
                comment.listing = listing
                comment.user = request.user
                comment.save()
                return redirect('listing_detail', listing_id=listing.id)
        else:
            return redirect('login')
    else:
        form = CommentForm()


    return render(request, 'marketplace/listing_detail.html', {
        'listing': listing,
        'is_owner': is_owner,
        'comments': comments,
        'form': form,
        'average_rating': average_rating,
        'reviews': reviews,

    })




def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, f"Registrazione completata con successo! Benvenuto su GameHistory Project")
            return redirect('home')
    else:
        form = UserCreationForm()
    return render(request, 'marketplace/registration/signup.html', {'form': form})

@login_required
def create_listing(request):
    if request.method == 'POST':
        listing_form = ListingForm(request.POST)
        game_form = GameForm(request.POST)

        if listing_form.is_valid() and game_form.is_valid():
            game_instance = game_form.save()  # Salva il gioco nel database
            listing_instance = listing_form.save(commit=False)
            if listing_instance.price > 0:
                listing_instance.game = game_instance
                listing_instance.user = request.user  # Associa l'utente corrente
                listing_instance.save()
                messages.success(request, f"Annuncio inserito con successo!")
                return redirect('home')
            else:
                messages.error(request, f"Non è possibile avere un prezzo in negativo!")
    else:
        listing_form = ListingForm()
        game_form = GameForm()


    return render(request, 'marketplace/create_listing.html', {
        'listing_form': listing_form,
        'game_form': game_form,
    })

@login_required
def add_game(request):
    if request.method == 'POST':
        form = GameForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = GameForm()
    return render(request, 'marketplace/add_game.html', {'form': form})


@login_required
@require_POST
def delete_listing(request, listing_id):
    listing = get_object_or_404(Listing, pk=listing_id)
    if request.user == listing.user:
        listing.delete()
        messages.success(request, 'Annuncio eliminato con successo!')
    return redirect('home')

@login_required
@require_POST
def buy_listing(request, listing_id):
    listing = get_object_or_404(Listing, pk=listing_id)

    if request.method == 'POST':
        if request.user.is_authenticated:
            if listing.quantity > 0:
                purchase = Purchase(user=request.user, listing=listing)
                purchase.save()

                listing.quantity -= 1

                if listing.quantity == 0:
                    listing.is_available = False

                listing.save()

                messages.success(request, 'Acquisto completato con successo!')
                return redirect('home')
            else:
                messages.error(request, 'L\'annuncio è esaurito.')
        else:
            if isinstance(request.user, AnonymousUser):
                return redirect('login') 
            else:
                messages.error(request, 'Devi effettuare il login per poter acquistare.')

    return render(request, 'listing_detail.html', {'listing': listing})


@login_required
def user_purchases(request):
    purchases = Purchase.objects.filter(user=request.user)
    return render(request, 'marketplace/user_purchases.html', {'purchases': purchases})

@login_required
def user_profile(request):
    user = request.user

    # acquisti dell'utente
    purchases_no_offer = Purchase.objects.filter(user=user, is_a_offer=False)
    purchases_offer = Purchase.objects.filter(user=user, is_a_offer=True)

    # annunci dell'utente ancora online
    active_listings = Listing.objects.filter(user=user, is_available=True)
    inactive_listings = Listing.objects.filter(user=user, is_available=False)
    
    # recensioni dell'utente
    reviews = Review.objects.filter(seller=user)
    average_rating = reviews.aggregate(models.Avg('rating'))['rating__avg']

    # logica delle offerte
    accepted_offers_as_buyer = Offer.objects.filter(user=user, accepted=True)
    accepted_offers_as_seller = Offer.objects.filter(listing__user=user, accepted=True)
    offers = Offer.objects.filter(listing__user=user, accepted=None)  # Solo le offerte non ancora accettate o rifiutate

    return render(request, 'marketplace/user_profile.html', {
        'user': user,
        'purchases_no_offer': purchases_no_offer,
        'purchases_offer': purchases_offer,
        'active_listings': active_listings,
        'inactive_listings': inactive_listings,
        'accepted_offers_as_buyer': accepted_offers_as_buyer,
        'accepted_offers_as_seller': accepted_offers_as_seller,
        'offers': offers,
        'average_rating': average_rating,
        'reviews': reviews,
    })

def search_listings(request):
    query = request.GET.get('query')
    listings = Listing.objects.filter(is_available=True)

    if query:
        listings = listings.filter(
            Q(game__title__icontains=query) |
            Q(game__genre__icontains=query)
        )

    return render(request, 'marketplace/search_results.html', {
        'listings': listings,
        'query': query,
    })


# NECESSARIA PER AVERE LA POSSIBILITA' DI AGGIUNGERE UNA NUOVA QUANTITA' AGLI ANNUNCIO DELL'UTENTE REGISTRATO.
@login_required
@require_POST
def add_quantity(request, listing_id):
    listing = get_object_or_404(Listing, id=listing_id, user=request.user)
    quantity_to_add = int(request.POST['quantity'])

    if quantity_to_add > 0:
        listing.quantity += quantity_to_add
        listing.save()

GameHistory Project/videogame_keys/marketplace/templates/marketplace/add_review.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Recensione per {{ listing.game.title }}</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
        .description-box {
            background-color: #f8f9fa;
            border: 1px solid #e9ecef;
            border-radius: 5px;
            padding: 20px;
            margin-bottom: 20px;
        }
        html, body {
            height: 100%;
        }
        body {
            display: flex;
            flex-direction: column;
        }
        .flex-grow-1 {
            flex-grow: 1;
        }
        .footer {
            background-color: #f8f9fa;
            border-top: 1px solid #e9ecef;
            padding: 10px 0;
            text-align: center;
            width: 100%;
            margin-top: auto;
        }   
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'home'%}">GameHistory Project</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user_profile' %}">Il tuo account</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'manage_offers' %}">Gestione offerte</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'create_listing' %}">Crea annuncio</a>
                    </li>
                    {% if user.is_superuser %}
                    <li class="nav-item">
                        <a class="btn btn-outline-danger" href="{% url 'admin:index' %}">Admin Dashboard</a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <form method="post" action="{% url 'logout' %}" class="form-inline">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-outline-danger">Logout</button>
                        </form>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'admin:index' %}">Login Admin</a>
                    </li>
                    <li class="nav-item">
                        <a class="btn btn-primary" href="{% url 'signup' %}">Registrati</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container mt-4">
        <h1 class="mb-4">Aggiungi una recensione al venditore per il titolo: {{ listing.game.title }}</h1>
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_rating">Voto (1-10)</label>
                        {{ form.rating }}
                        <script>
                            document.getElementById('id_rating').setAttribute('min', 1);
                            document.getElementById('id_rating').setAttribute('max', 10);
                            document.getElementById('id_rating').classList.add('form-control');
                        </script>
                        {% if form.rating.errors %}
                            <div class="invalid-feedback d-block">
                                {{ form.rating.errors }}
                            </div>
                        {% endif %}
                    </div>
                    <div class="form-group">
                        <label for="id_comment">Descrivi il perchè di questo voto</label>
                        {{ form.comment }}
                        <script>
                            document.getElementById('id_comment').classList.add('form-control');
                        </script>
                        {% if form.comment.errors %}
                            <div class="invalid-feedback d-block">
                                {{ form.comment.errors }}
                            </div>
                        {% endif %}
                    </div>
                    <button type="submit" class="btn btn-primary">Invia recensione</button>
                </form>
            </div>
        </div>
    </div>
    <footer class="footer">
        <p>&copy; 2024 GameHistory Project. Tutti i diritti riservati.</p>
    </footer>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

GameHistory Project/videogame_keys/marketplace/templates/marketplace/create_offer.html
<!DOCTYPE html>
<html>
<head>
    <title>Crea Offerta</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
        html, body {
            height: 100%;
        }
        body {
            display: flex;
            flex-direction: column;
        }
        .flex-grow-1 {
            flex-grow: 1;
        }
        .footer {
            background-color: #f8f9fa;
            border-top: 1px solid #e9ecef;
            padding: 10px 0;
            text-align: center;
            width: 100%;
            margin-top: auto;
        }   
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'home'%}">GameHistory Project</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user_profile' %}">Il tuo account</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'manage_offers' %}">Gestione offerte</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'create_listing' %}">Crea annuncio</a>
                    </li>
                    {% if user.is_superuser %}
                    <li class="nav-item">
                        <a class="btn btn-outline-danger" href="{% url 'admin:index' %}">Admin Dashboard</a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <form method="post" action="{% url 'logout' %}" class="form-inline">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-outline-danger">Logout</button>
                        </form>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'admin:index' %}">Login Admin</a>
                    </li>
                    <li class="nav-item">
                        <a class="btn btn-primary" href="{% url 'signup' %}">Registrati</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="container mt-5 flex-grow-1">
        <div class="card shadow-sm">
            <div class="card-header bg-primary text-white">
                <h1 class="h4 mb-0">Crea Offerta per {{ listing.game.title }}</h1>
            </div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_offer_price" class="font-weight-bold">Prezzo dell'offerta</label>
                        {{ form.offer_price }}
                        <div class="product-info mt-2">
                            <p class="font-weight-bold">Prezzo attuale dell'annuncio: €{{ listing.price }}</p>
                            {% if messages %}
                                <div class="alert alert-info">
                                {% for message in messages %}
                                    <p>{{ message }}</p>
                                {% endfor %}
                                </div>
                            {% endif %}
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary btn-block">Invia Offerta</button>
                </form>
            </div>
        </div>
    </div>
    <footer class="footer">
        <p>&copy; 2024 GameHistory Project. Tutti i diritti riservati.</p>
    </footer>    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>